### ISSUE TITLE
Loading files into super-reconstruction analyses

### ISSUE THREAD

**Issue by jefflamyl** [zengjiexia/ACT#15]
![image](https://user-images.githubusercontent.com/102862604/161384475-33ace104-4e35-49a3-a5c3-01faf21db867.png)
Cannot load files from Dropbox (local files) into the super-reconstruction Analysis, as attached.
However, these files, same location, can be loaded to the Diffraction-Limited Analyses.

**Comment by zengjiexia** [comment]
**The issue has been resolved in the latest update of v2-development branch.**
