### ISSUE TITLE
Analysed data missing in super-reconstruction analyses

### ISSUE THREAD

**Issue by jefflamyl** [zengjiexia/ACT#18]
![image](https://user-images.githubusercontent.com/102862604/161385351-920334e7-9fb8-45f4-ac34-96ff15b5792d.png)
I now have two videos super-constructed and drift corrected. Well done.
Tried filtering and cluster analyses, a couple of problems exist. I also have one more suggestion.
Problems:
1. Files for the second video missing, both filtered and clustered.csv - as shown in the attached picture.
2. Summary file for all videos missing.
Suggestion:
It would also be great if you can add a suffix in the _clustered.csv file as _clustered_75_2.csv to indicate the parameters (eps and min sample) used for DBSCAN.

**Comment by jefflamyl** [comment]
![image](https://user-images.githubusercontent.com/102862604/161386417-d3b8aa8f-d0e0-49f1-814b-6d09100223e0.png)

**Comment by zengjiexia** [comment]
**The issue has been resolved in the latest update of v2-development branch.**
